---
- name: Install nginx
  apt: name=nginx state=latest
  notify: restart nginx

- name: Copy nginx configuration for host
  template:
    src: www.conf
    dest: /etc/nginx/sites-available/www.conf
    mode: 0644
  notify: restart nginx

- name: Create symlink for nginx configuration
  file: src=/etc/nginx/sites-available/www.conf
        dest=/etc/nginx/sites-enabled/default owner=root group=root state=link
  notify: restart nginx

- name: Install php-fpm
  apt: name=php-fpm state=latest
  notify:
    - restart php-fpm
    - restart nginx

- name: Copy php-fpm configuration for host
  copy: src=php.ini dest=/etc/php/7.0/fpm/ owner=root group=root mode=0644
  notify: restart php-fpm

- name: Install php-xdebug
  apt: name=php-xdebug state=latest

- name: Copy xdebug configuration file
  template:
    src: xdebug.ini
    dest: /etc/php/7.0/mods-available/xdebug.ini
    mode: 0644
  notify: restart php-fpm

- name: Сreate log directory if it doesn't exist
  file:
    path: /vagrant/log
    state: directory
    mode: 0755

- name: Install PHPUnit
  copy:
    src: phpunit.phar
    dest: /usr/local/bin/phpunit
    mode: 0555

- name: Create phpdoc directory
  file:
    path: "{{ phpdoc_dir }}"
    state: directory
    mode: 0755

- name: Extract phpDocumentor
  unarchive:
    src: phpDocumentor.tgz
    dest: "{{ phpdoc_dir }}"   
    mode: 0555
    keep_newer: yes

- name: Create symlink for phpdoc
  file:
    src: "{{ phpdoc_dir }}/phpDocumentor-{{ phpdoc_version }}/bin/phpdoc"
    dest: /usr/local/bin/phpdoc
    state: link

# Требуется для запуска phpdoc
- name: Install php-dom
  apt: name=php-dom state=latest
  notify:
    - restart php-fpm 